# SPDX-License-Identifier: Apache-2.0
"""Generate folk_aligned.ttl from ThatsAllFolks/folk.ttl.

The two files held the same ontology in two serializations, maintained by hand
in parallel. Measured before this was written: 473 named subjects each with
none unique to either side, matching counts across every predicate, and a
ground difference of five ontology-metadata statements — plus blank-node
identity, which is the only reason the graphs were not isomorphic.

Two files saying the same thing do not need a winner chosen between them. They
need one generated from the other, after which they cannot drift.

**`ThatsAllFolks/folk.ttl` is the authored source.** It carries the labels,
comments and provenance that `folk_aligned.ttl`'s declaration blocks omit, it
sits with the 127 fragments, and it is where new value declarations have been
going. `folk_aligned.ttl` already announced itself as machine-written — its
last line reads "Generated by the OWL API" — so this makes true what the file
already claimed.

**Determinism.** rdflib's Turtle writer orders output by dictionary iteration,
so adding one triple can reshuffle unrelated blocks and produce a diff that is
all noise. This serializes by hand: subjects sorted by IRI, predicates sorted
within a subject, objects sorted within a predicate, and blank nodes written
inline as nested `[ ]` so they never need a label. The same input gives the
same bytes, which is what makes a staleness check in CI meaningful rather than
a source of spurious failures.

Blank-node *identity* is deliberately not preserved, and does not need to be:
the restrictions are structurally identical, and two graphs differing only in
bnode labels say the same thing.

    python tools/original-valuenet/generate_folk_aligned.py [--check]

`--check` regenerates in memory and reports whether the committed file is
stale, without writing. That is what CI runs.
"""

from __future__ import annotations

import argparse
import os
import sys

try:
    import rdflib
    from rdflib.namespace import OWL, RDF
except ImportError:  # pragma: no cover
    sys.exit("needs rdflib: pip install rdflib")

# Root and paths come from the layout contract. Counting parents breaks when
# this file moves to tools/original-valuenet/, one level deeper.
_here = os.path.abspath(__file__)
_root = _here
while not os.path.isfile(os.path.join(_root, "config", "repository-layout.yaml")):
    _parent = os.path.dirname(_root)
    if _parent == _root:
        raise SystemExit("no config/repository-layout.yaml above " + _here)
    _root = _parent
sys.path.insert(0, _root)

from marep import layout  # noqa: E402

HERE = layout.repository_root().as_posix()
SOURCE = str(layout.path("original-valuenet.folk-source"))
TARGET = str(layout.path("original-valuenet.folk-aligned"))

#: Both paths come from the contract. The Generator line was written
#: literally, so after the original-valuenet wave regenerating this
#: file would have re-emitted `ValueNet_code/...` -- and the layout
#: contract declares an allowance for that literal with
#: `remove_after_wave: original-valuenet`, an action that regeneration
#: could never have carried out. Today both resolve to their current
#: paths, so the generated bytes are unchanged.
GENERATOR_PATH = layout.relative(
    layout.component("tool.generate-folk-aligned").resolve())

HEADER = f"""# =====================================================================
# GENERATED FILE - DO NOT EDIT BY HAND
#
# Source:    {layout.relative(SOURCE)}
# Generator: {GENERATOR_PATH}
#
# Edits made here are lost the next time the generator runs, and CI fails
# when this file is stale relative to its source. Change folk.ttl instead.
#
# This is a canonical re-serialization: subjects, predicates and objects are
# emitted in sorted order and blank nodes inline, so the same source always
# produces the same bytes.
# =====================================================================
"""

#: Prefixes, fixed rather than inherited, so a prefix added to the source for
#: one file's convenience cannot reorder this one's header.
PREFIXES = [
    ("bhv", "https://w3id.org/spice/SON/SchwartzValues#"),
    ("dul", "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#"),
    ("folk", "http://www.ontologydesignpatterns.org/ont/values/FolkValues.owl#"),
    ("fschema", "https://w3id.org/framester/schema/"),
    ("mft", "https://w3id.org/spice/SON/HaidtValues#"),
    ("owl", "http://www.w3.org/2002/07/owl#"),
    ("prov", "http://www.w3.org/ns/prov#"),
    ("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#"),
    ("rdfs", "http://www.w3.org/2000/01/rdf-schema#"),
    ("skos", "http://www.w3.org/2004/02/skos/core#"),
    ("vcvf", "http://www.ontologydesignpatterns.org/ont/values/"
             "valuecore_with_value_frames.owl#"),
    ("xsd", "http://www.w3.org/2001/XMLSchema#"),
]


def qname(term, prefixes):
    s = str(term)
    for pre, uri in prefixes:
        if s.startswith(uri) and "/" not in s[len(uri):]:
            local = s[len(uri):]
            if local and not local[0].isdigit():
                return f"{pre}:{local}"
    return f"<{s}>"


def literal(term) -> str:
    text = str(term)
    for bad, good in (("\\", "\\\\"), ('"', '\\"'), ("\n", "\\n"), ("\r", "\\r")):
        text = text.replace(bad, good)
    out = f'"{text}"'
    if term.language:
        out += f"@{term.language}"
    elif term.datatype:
        out += f"^^<{term.datatype}>"
    return out


def render(term, graph, prefixes, depth=0):
    """One term. Blank nodes recurse inline, so no labels are ever needed."""
    if isinstance(term, rdflib.BNode):
        pad = "    " * (depth + 1)
        parts = []
        for p in sorted(set(graph.predicates(term, None)), key=str):
            for o in sorted(set(graph.objects(term, p)), key=str):
                parts.append(f"{pad}{qname(p, prefixes)} "
                             f"{render(o, graph, prefixes, depth + 1)}")
        if not parts:
            return "[]"
        return "[\n" + " ;\n".join(parts) + "\n" + "    " * depth + "]"
    if isinstance(term, rdflib.Literal):
        return literal(term)
    return qname(term, prefixes)


def serialize(graph) -> str:
    out = [HEADER]
    for pre, uri in PREFIXES:
        out.append(f"@prefix {pre}: <{uri}> .")
    out.append("")

    # Only named subjects get their own block. A blank node is always reached
    # from the subject that references it, and emitting it separately would
    # produce an orphan.
    subjects = sorted({s for s in graph.subjects() if not isinstance(s, rdflib.BNode)},
                      key=str)
    # The ontology declaration leads, as in any hand-written module.
    onts = [s for s in subjects if (s, RDF.type, OWL.Ontology) in graph]
    subjects = onts + [s for s in subjects if s not in onts]

    for s in subjects:
        lines = []
        for p in sorted(set(graph.predicates(s, None)), key=str):
            for o in sorted(set(graph.objects(s, p)), key=str):
                lines.append(f"    {qname(p, PREFIXES)} "
                             f"{render(o, graph, PREFIXES, 1)}")
        if lines:
            out.append(f"{qname(s, PREFIXES)}")
            out.append(" ;\n".join(lines) + " .")
            out.append("")
    return "\n".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report staleness without writing; this is what CI runs")
    args = ap.parse_args(argv)

    source = rdflib.Graph()
    source.parse(SOURCE, format="turtle")
    generated = serialize(source)

    existing = ""
    if os.path.exists(TARGET):
        with open(TARGET, encoding="utf-8", newline="") as fh:
            existing = fh.read()

    if existing.replace("\r\n", "\n") == generated.replace("\r\n", "\n"):
        print(f"up to date: {os.path.relpath(TARGET, HERE)} matches its source")
        return 0

    if args.check:
        print(f"STALE: {os.path.relpath(TARGET, HERE)} does not match "
              f"{os.path.relpath(SOURCE, HERE)}.", file=sys.stderr)
        print("Run: python " + GENERATOR_PATH, file=sys.stderr)
        return 1

    with open(TARGET, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(generated)
    print(f"wrote {os.path.relpath(TARGET, HERE)} "
          f"({len(generated):,} chars) from {os.path.relpath(SOURCE, HERE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
