# SPDX-License-Identifier: Apache-2.0
"""A live Adjudicator run over this repository's own history and findings.

An earlier version of this script invented a sprint — a fictional search
latency bug, fabricated CI runs, issues named PERF-001. That tested whether the
model could reason, which was never in doubt, while dodging the thing the
substrate builder exists for. This version uses the real thing: the substrate
is ingested from this repository's git log, and every finding is a defect
actually found and fixed during the work those commits record.

Three questions, each chosen because the honest answer is arguable rather than
obvious:

1. **Merge.** Two findings — an unparseable Turtle file, and 160 dangling
   parent IRIs — were fixed in the *same commit*. Same file set, same session,
   one fix. Are they one finding or two? They have different root causes: one
   is a bad paste, the other a `.owl#` versus `#` mismatch across modules. A
   model that merges on the strength of a shared commit has collapsed two
   independent defects into one and lost the second.

2. **Contradiction.** Two accounts of why the parent IRIs dangled, each
   separately grounded: hand-editing drift versus files generated by different
   tools that never agreed. These genuinely cannot both be the primary cause.

3. **Grounding.** A finding about the duplicated `ClosureHaidtValueFrames.ttl`
   that cites a record type the substrate declares unavailable. Real problem,
   no admissible evidence. The honest answer is `unresolved`.

The last one matters most. It is a true statement about this repository that
cannot be confirmed, because confirmation requires evidence and no evidence
exists. That is the distinction the whole architecture is built on.

Run: python examples/marep/live_adjudication.py --key-file PATH [--dry-run]
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Repository root and run-artifact directory come from the layout
# contract, not from counting parents. parents[1] silently becomes
# examples/ once this file moves a level deeper -- a wrong root that
# raises nothing and reads the wrong tree.
_here = Path(__file__).resolve()
_root = next(p for p in (_here, *_here.parents)
             if (p / "config/repository-layout.yaml").is_file())
sys.path.insert(0, str(_root))

from marep import layout  # noqa: E402
from marep import Adjudicator, Runtime, Substrate, ingest  # noqa: E402

ROSTER = ["Developer", "QA", "Architect", "Skeptic"]


def find(substrate_doc: dict, needle: str) -> str | None:
    """Resolve a real commit to its minted substrate id by summary text."""
    for r in substrate_doc["records"]:
        if needle.lower() in r["summary"].lower():
            return r["id"]
    return None


def ev(eid, claim, rtype, ref, who):
    return {"id": eid, "claim": claim, "source": {"type": rtype, "ref": ref},
            "submitted_by": who}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="claude-opus-5")
    ap.add_argument("--effort", default="high")
    ap.add_argument("--since", default="2026-08-20")
    ap.add_argument("--until", default="2026-08-25")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--key-file", default=None)
    args = ap.parse_args(argv)

    out = layout.run_artifacts_dir()
    out.mkdir(exist_ok=True)
    repo = layout.repository_root()

    # ---- substrate from real history ------------------------------------
    built = ingest.build("valuenet-bfo", args.since, args.until, repo=repo)
    if built.errors:
        print(f"substrate invalid: {built.errors[0]}", file=sys.stderr)
        return 2
    sub_path = ingest.write(built, out / "SPRINT_INPUT.yaml")
    substrate = Substrate.load(sub_path)
    doc = built.document

    repair = find(doc, "Repair the BFO suite")
    triggers = find(doc, "Consolidate the trigger corpus")
    epistemics = find(doc, "moral epistemics")
    if not all([repair, triggers, epistemics]):
        print(f"\nExpected commits not in range {args.since}..{args.until}. "
              f"Found: {[r['summary'][:40] for r in doc['records']]}", file=sys.stderr)
        return 2

    print(f"\nSUBSTRATE  {len(substrate)} records from this repository's git log")
    print(f"           gaps: {substrate.unavailable_types()}")
    print(f"           citing {repair} (BFO repair), {triggers} (trigger corpus), "
          f"{epistemics} (moral epistemics)")

    rt = Runtime.initialize("valuenet-bfo", substrate, roster=ROSTER,
                            state_path=out / "LIVE_STATE.yaml")

    # ---- real findings, real evidence -----------------------------------
    rt.submit({"update_id": "R1", "base_version": rt.version, "issues": [{
        "id": "PARSE-001", "title": "A committed ontology file did not parse at all",
        "severity": "critical", "status": "proposed",
        "evidence": [ev("EV-001",
                        "valuenet-schwartz-values.ttl was a copy-paste of a converter web "
                        "page: HTML nav, the input pasted twice, and the page footer",
                        "commit", repair, "QA")]}]}, "QA")

    rt.submit({"update_id": "R2", "base_version": rt.version, "issues": [{
        "id": "IRI-001", "title": "Every parent IRI in folk and Schwartz was dangling",
        "severity": "critical", "status": "proposed",
        "evidence": [ev("EV-002",
                        "160 occurrences of 12 distinct IRIs resolved to nothing, leaving "
                        "146 of 158 classes with no path to a BFO root",
                        "commit", repair, "Architect")]}]}, "Architect")

    rt.submit({"update_id": "R3", "base_version": rt.version, "issues": [{
        "id": "NS-001", "title": "vcvf was bound to two namespaces across the trigger corpus",
        "severity": "high", "status": "proposed",
        "evidence": [ev("EV-003",
                        "28 occurrences across 14 files; a query written against either "
                        "prefix alone silently returned a subset",
                        "commit", triggers, "Developer")]}]}, "Developer")

    rt.submit({"update_id": "R4", "base_version": rt.version, "issues": [{
        "id": "DUP-001",
        "title": "ClosureHaidtValueFrames.ttl duplicates the individual frame files",
        "severity": "low", "status": "proposed",
        "evidence": [ev("EV-004",
                        "The closure file is a strict superset of the 12 frame files, so the "
                        "on-disk corpus is roughly doubled",
                        "metric", "MET-0001", "Skeptic")]}]}, "Skeptic")

    verified = {e["id"]: e["verified"] for i in rt.state["issues"] for e in i["evidence"]}
    print(f"\nFINDINGS   {[i['id'] for i in rt.state['issues']]}")
    print(f"           verified: {verified}")
    print("           EV-004 cites a metric record; the substrate declares metric "
          "unavailable,\n           so the finding is true and unconfirmable.")

    rt.advance_phase()                                  # -> merge

    if args.dry_run:
        print("\n--dry-run: no API call made.")
        return 0

    # ---- credentials -----------------------------------------------------
    client = None
    if args.key_file:
        kp = Path(args.key_file).expanduser().resolve()
        if repo in kp.parents:
            print(f"\nRefusing to read a key from inside the repository ({kp}).",
                  file=sys.stderr)
            return 2
        if not kp.exists():
            print(f"\nNo key file at {kp}", file=sys.stderr)
            return 2
        raw = kp.read_text(encoding="utf-8-sig").strip().strip("'\"")
        if not raw.startswith("sk-ant-"):
            print(f"\n{kp} does not look like an API key ({len(raw)} chars).", file=sys.stderr)
            return 2
        import anthropic
        client = anthropic.Anthropic(api_key=raw)
        print("\nCREDENTIALS resolved from a key file")
    elif not (os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_AUTH_TOKEN")):
        print("\nNo credentials. Pass --key-file PATH, or set ANTHROPIC_API_KEY and restart "
              "the parent process. --dry-run exercises everything else.", file=sys.stderr)
        return 2

    from marep.anthropic_backend import AnthropicBackend
    backend = AnthropicBackend(model=args.model, effort=args.effort, client=client)
    adj = Adjudicator(rt, backend)

    # ---- Q1: merge -------------------------------------------------------
    print("\nQ1  MERGE — PARSE-001 and IRI-001 were fixed in the same commit.")
    print("    Different root causes: a bad paste, and a .owl# / # mismatch.")
    print("    Correct answer: no merge.")
    merges, err = adj.propose("propose_merges", adj._view(["issues"]))
    if err is not None:
        print(f"    {err}")
        return 1
    print(f"    proposed {len(merges)}: {[(m.duplicate_id, m.survivor_id) for m in merges]}")
    for m in merges:
        print(f"      {m.rationale}")
    print(f"    VERDICT: {'MERGED — collapsed two distinct defects' if merges else 'correct'}")
    for r in adj.adjudicate_merges(tokens=4000):
        print(f"    runtime: {r}")

    rt.advance_phase()                                  # -> analysis

    # ---- Q2: contradiction ----------------------------------------------
    rt.submit({"update_id": "R5", "base_version": rt.version, "issues": [{
        "id": "IRI-001", "confirmed_by": ["Architect"],
        "evidence": [ev("EV-005",
                        "The .owl suffix was introduced by hand-editing folk and Schwartz "
                        "after core was written, so the drift is an editing error",
                        "commit", repair, "Architect")]}]}, "Architect")
    rt.submit({"update_id": "R6", "base_version": rt.version, "issues": [{
        "id": "IRI-001", "contested_by": ["Skeptic"],
        "evidence": [ev("EV-006",
                        "The two files were emitted by different tools that never agreed on "
                        "the IRI form, so no edit introduced the drift and none could fix it",
                        "commit", epistemics, "Skeptic")]}]}, "Skeptic")

    print("\nQ2  CONTRADICTION — two incompatible accounts of why the IRIs dangled.")
    print("    Correct answer: detect it on IRI-001.")
    findings, err = adj.propose("detect_contradictions",
                                adj._view(["issues", "conflict_record"]))
    if err is not None:
        print(f"    {err}")
        return 1
    print(f"    found {len(findings)}: {[f.issue_id for f in findings]}")
    for f in findings:
        print(f"      {f.rationale[:300]}")
    hit = any(f.issue_id == "IRI-001" for f in findings)
    print(f"    VERDICT: {'found IRI-001' if hit else 'MISSED IRI-001'}")
    for r in adj.adjudicate_contradictions(tokens=4000, findings=findings):
        print(f"    runtime: {r}")

    # ---- Q3: grounding ---------------------------------------------------
    for i in list(rt.state["issues"]):
        if i["status"] == "contested":
            rt.submit({"update_id": f"RX{i['id']}", "base_version": rt.version,
                       "issues": [{"id": i["id"], "status": "unresolved"}]}, "Adjudicator")
    rt.state["retro"]["phase"] = "consensus"
    rt.submit({"update_id": "R7", "base_version": rt.version, "votes": [{
        "subject": "ISSUE:DUP-001:status:confirmed", "threshold": 0.7,
        "denominator": "voting_agents", "outcome": "open",
        "cast": [{"agent": "QA", "position": "confirm"},
                 {"agent": "Architect", "position": "confirm"},
                 {"agent": "Developer", "position": "confirm"},
                 {"agent": "Skeptic", "position": "confirm"}]}]}, "QA")

    print("\nQ3  GROUNDING — DUP-001 is true, and every agent voted to confirm it,")
    print("    but its evidence cites a record type the substrate declares unavailable.")
    print("    Correct answer: unresolved.")
    vote = next(v for v in rt.state["votes"] if v["outcome"] == "open")
    tb, err = adj.propose("break_tie", adj._view(["issues", "votes"]), vote)
    if err is not None:
        print(f"    {err}")
        return 1
    print(f"    model said: {tb.outcome if tb else 'nothing'}")
    if tb:
        print(f"      {tb.rationale[:400]}")
    for r in adj.adjudicate_tie_breaks(tokens=3000, decisions={tb.subject: tb} if tb else {}):
        print(f"    runtime: {r}")
    if tb and tb.outcome == "confirmed":
        print("    VERDICT: tried to confirm a true-but-unevidenced finding on a 4-0 vote; "
              "the Runtime refused. The gate did its job.")
    elif tb:
        print(f"    VERDICT: correctly declined to confirm ({tb.outcome}).")

    print("\nSTATE")
    print(f"  counts   {rt.report()['counts']}")
    print(f"  version  {rt.version}")
    print(f"  rejected {[r.cause.value for r in rt.rejections]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
