"""Derive the reorganization move manifest from the repository, not by hand.

The first two drafts of the plan listed destinations by reading the file tree
and typing them out. That missed six files — `valuenet-mappings.ttl`,
`vcvf-triggers-semantics.ttl`, `vcvf-triggers-review.md`, two Phase 1 term
documents, and an upstream tool — and misclassified `wvs.ttl` as fork-authored
when it is a rename of upstream's `wvs.owl`. Both failures are what hand-listing
does at this scale.

Two rules, applied mechanically:

**Provenance is two orthogonal axes**, because "fork-authored", "generated" and
"vendored" are not mutually exclusive. `bfo-core.ttl` is external BFO,
unchanged. The CCO extract is external CCO, generated. `folk_aligned.ttl` is
upstream-derived content, generated. `wvs.ttl` is upstream, renamed.

    origin      : upstream-valuenet | fork | external-bfo | external-cco
    maintenance : unchanged | locally-modified | generated

**Origin follows rename history.** `git log --follow` rather than comparing
current filename sets, which is what misfiled `wvs.ttl`.

Under the settled rule, anything whose origin is `upstream-valuenet` is
RETAINED at its current path regardless of maintenance state, including
documentation assets. Only fork and external material moves.

    python ValueNet_code/build_move_manifest.py [-o config/move-manifest.yaml]
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sh(*args: str) -> str:
    return subprocess.run(args, capture_output=True, text=True, cwd=HERE).stdout


def tracked() -> list[str]:
    return [p for p in sh("git", "ls-tree", "-r", "--name-only", "HEAD").split("\n") if p]


def upstream_paths() -> set[str]:
    return {p for p in sh("git", "ls-tree", "-r", "--name-only",
                          "upstream/main").split("\n") if p}


def first_commit_subject(path: str) -> str:
    """Oldest commit touching this path, following renames."""
    out = sh("git", "log", "--follow", "--format=%H", "--", path).split("\n")
    shas = [s for s in out if s]
    if not shas:
        return ""
    return sh("git", "log", "-1", "--format=%s", shas[-1]).strip()


#: Files generated by a tool in this repository, and by which component.
GENERATED = {
    "folk_aligned.ttl": "tool:generate-folk-aligned",
    "BFO/imports/cco-valuenet-extract.ttl": "tool:generate-cco-extract",
    "BFO/imports/cco-valuenet-extract.manifest.json": "tool:generate-cco-extract",
}

#: Upstream descent that git cannot detect, asserted with its reason.
#:
#: Rename-following has a limit: git records a rename only when content
#: similarity clears its threshold. Two files here descend from upstream by
#: an edit large enough to hide that.
#:
#:   ThatsAllFolks/folk.ttl        converted from upstream folk.owl, RDF/XML
#:                                 to Turtle, which rewrites every line
#:   ThatsAllFolks/folk_Religion.ttl  renamed from upstream folk_Belief.ttl
#:                                 while retargeting 623 trigger statements
#:
#: Asserted rather than derived, because the alternative is a classifier that
#: silently calls upstream content fork-authored and then moves it.
KNOWN_UPSTREAM_DESCENT = {
    "ThatsAllFolks/folk.ttl":
        "converted from upstream ThatsAllFolks/folk.owl (RDF/XML to Turtle)",
    "ThatsAllFolks/folk_Religion.ttl":
        "renamed from upstream ThatsAllFolks/folk_Belief.ttl during retargeting",
}


#: Path-sensitive configuration. Invisible to a .py/.ttl sweep, which is why
#: .gitignore was missed twice — and moving examples/ without it would have
#: started committing 1,127,251 bytes of run state.
CONFIG_FILES = {".gitignore", "pytest.ini", "README.md",
                ".github/workflows", "pyproject.toml", "tox.ini", "setup.cfg"}

DESTINATIONS: list[tuple[str, str]] = [
    ("BFO/imports/", "ontology/bfo/vendor/cco/"),
    ("BFO/bfo-core.ttl", "ontology/bfo/vendor/bfo/bfo-core.ttl"),
    ("BFO/remediation/generate_cco_extract.py", "tools/bfo/generate_cco_extract.py"),
    ("BFO/remediation/check_bfo_consistency.py", "tools/bfo/check_bfo_consistency.py"),
    ("BFO/remediation/extract-manifest.schema.json",
     "tools/bfo/extract-manifest.schema.json"),
    ("BFO/remediation/", "docs/bfo/remediation/"),
    ("BFO/valuenet-moral-epistemics", "ontology/bfo/extensions/moral-epistemics/"),
    ("BFO/valuenet-moral-foundations", "ontology/bfo/extensions/moral-foundations/"),
    ("BFO/vcvf-triggers-shapes.ttl", "ontology/bfo/shapes/vcvf-triggers-shapes.ttl"),
    ("BFO/vcvf-triggers-semantics.ttl",
     "ontology/bfo/extensions/trigger-semantics/vcvf-triggers-semantics.ttl"),
    ("BFO/vcvf-triggers-review.md", "docs/bfo/guides/vcvf-triggers-review.md"),
    ("BFO/valuenet-core-shapes.ttl", "ontology/bfo/shapes/valuenet-core-shapes.ttl"),
    ("BFO/valuenet-mappings.ttl", "ontology/bfo/core/valuenet-mappings.ttl"),
    ("BFO/valuenet-", "ontology/bfo/core/"),
    ("BFO/", "docs/bfo/guides/"),
    ("ValueNet_code/is_v_emo_overlaps.py", "RETAIN"),
    ("ValueNet_code/report_run.py", "tools/marep/report_run.py"),
    ("ValueNet_code/", "tools/original-valuenet/"),
    ("examples/", "examples/marep/"),
    ("MAREP_v2.", "docs/marep/specifications/"),
    ("MAREP_RUN", "docs/marep/runs/"),
    ("MAREP_", "docs/marep/plans/"),
    ("REPO_REORGANIZATION_PLAN.md", "docs/architecture/"),
    ("tests/", "tests/"),
    ("marep/", "marep/"),
]


def destination(path: str, origin: str) -> str:
    if origin == "upstream-valuenet":
        return "RETAIN"
    if path in CONFIG_FILES or path.split("/")[0] in CONFIG_FILES:
        return "RETAIN"
    for prefix, dest in DESTINATIONS:
        if path.startswith(prefix):
            if dest in ("RETAIN", "tests/", "marep/"):
                return dest if dest == "RETAIN" else "REORGANIZE-IN-PLACE"
            tail = path[len(prefix):] if dest.endswith("/") else ""
            return dest + tail
    return "UNASSIGNED"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", default=None)
    args = ap.parse_args(argv)

    up = upstream_paths()
    rows = []
    for path in tracked():
        if path in up:
            origin = "upstream-valuenet"
            changed = sh("git", "diff", "--stat", "upstream/main", "HEAD", "--", path)
            maintenance = "locally-modified" if changed.strip() else "unchanged"
        elif path.startswith("BFO/imports/"):
            origin, maintenance = "external-cco", "generated"
        elif path.endswith("bfo-core.ttl"):
            origin, maintenance = "external-bfo", "unchanged"
        else:
            # A path absent upstream today may still descend from an upstream
            # file. wvs.owl became wvs.ttl, folk.owl became folk.ttl,
            # folk_Belief.ttl became folk_Religion.ttl. A name-set comparison
            # calls all three fork-authored; following rename history does not.
            origin = ("upstream-valuenet"
                      if path in KNOWN_UPSTREAM_DESCENT or _from_upstream(path, up)
                      else "fork")
            maintenance = "generated" if path in GENERATED else (
                "locally-modified" if origin == "upstream-valuenet" else "unchanged")
        rows.append({
            "path": path, "origin": origin, "maintenance": maintenance,
            "generated_from": GENERATED.get(path),
            "destination": destination(path, origin),
        })

    unassigned = [r for r in rows if r["destination"] == "UNASSIGNED"]
    print(f"  {len(rows)} tracked files")
    for key in ("RETAIN", "REORGANIZE-IN-PLACE", "UNASSIGNED"):
        print(f"    {sum(1 for r in rows if r['destination'] == key):>4}  {key}")
    print(f"    {sum(1 for r in rows if r['destination'] not in ('RETAIN', 'REORGANIZE-IN-PLACE', 'UNASSIGNED')):>4}  MOVE")
    if unassigned:
        print("\n  UNASSIGNED — the manifest is incomplete:")
        for r in unassigned[:20]:
            print(f"      {r['path']}")
    if args.out:
        import yaml
        with open(os.path.join(HERE, args.out), "w", encoding="utf-8", newline="\n") as fh:
            yaml.safe_dump({"components": rows}, fh, sort_keys=False)
        print(f"\n  wrote {args.out}")
    return 1 if unassigned else 0


def _from_upstream(path: str, up: set[str]) -> bool:
    """True when this path's history includes a name that upstream has."""
    names = sh("git", "log", "--follow", "--name-only", "--format=", "--", path)
    return any(n.strip() in up for n in names.split("\n") if n.strip())


if __name__ == "__main__":
    raise SystemExit(main())
